name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  bench:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run benchmark I
      run: cargo run -r -- -C codegen-units=1 -C opt-level=3

    - name: Run benchmark II
      run: cargo run -r -- -C codegen-units=1 -C opt-level=3

    - name: Run benchmark III
      run: cargo run -r -- -C codegen-units=1 -C opt-level=3
